-- Ali Baba Smoke Shop — placeholder catalog seed
-- Generated from lib/data/categories.ts and lib/data/products.ts via `npm run generate:seed`.
-- Run after schema.sql.

delete from order_items;
delete from orders;
delete from products;
delete from categories;

insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Vapes & Devices', 'vapes', 'Mods, pod systems, and starter kits.', 'Zap');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Disposables', 'disposables', 'Grab-and-go disposable vapes in every flavor.', 'Wind');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'E-Liquids', 'e-liquids', 'Bottled e-liquids and nic salts.', 'Droplet');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Glass & Water Pipes', 'glass', 'Hand pipes, bubblers, and water pipes.', 'CircleDot');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Hookah & Shisha', 'hookah', 'Hookahs, shisha flavors, and coals.', 'Flame');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Rolling Papers & Wraps', 'papers', 'Papers, cones, wraps, and filters.', 'Layers');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Grinders', 'grinders', 'Herb grinders in every size and finish.', 'Cog');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Lighters & Torches', 'lighters', 'Torch lighters, classics, and butane.', 'FlameKindling');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Smoking Accessories', 'accessories', 'Trays, cases, cleaners, and more.', 'Package');
insert into categories (id, name, slug, description, icon) values (gen_random_uuid(), 'Apparel & Merch', 'apparel', 'Shop tees, hats, and stickers.', 'Shirt');

insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-vape-001', 'Northbound Pro Mod Kit', 'northbound-pro-mod-kit', 'Adjustable-wattage box mod with dual 18650 battery bay and a 0.96" color display. Includes coils and USB-C cable.', 5999, 'vapes', 'Northbound', 'vape-001', true, true);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-vape-002', 'Oasis Pod System Starter Kit', 'oasis-pod-starter-kit', 'Compact pod-based system with magnetic pod connection and adjustable airflow. Great for beginners.', 2999, 'vapes', 'Oasis', 'vape-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-vape-003', 'Ember & Oak Replacement Coils (5-pack)', 'ember-oak-replacement-coils', 'Mesh replacement coils compatible with most standard pod systems.', 1499, 'vapes', 'Ember & Oak', 'vape-003', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-vape-004', 'Bazaar Blend Sub-Ohm Tank', 'bazaar-blend-sub-ohm-tank', '5mL sub-ohm tank with top-fill design and adjustable bottom airflow.', 3499, 'vapes', 'Bazaar Blend', 'vape-004', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-disp-001', 'Genie''s Choice 5000 Puff Disposable', 'genies-choice-5000-disposable', 'Rechargeable disposable with mesh coil, available in assorted fruit flavors.', 1799, 'disposables', 'Genie''s Choice', 'disp-001', true, true);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-disp-002', 'Sultan''s Reserve Mini Disposable', 'sultans-reserve-mini-disposable', 'Pocket-sized disposable, 600 puffs, draw-activated.', 999, 'disposables', 'Sultan''s Reserve', 'disp-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-disp-003', 'Lamp & Vine 10000 Puff Disposable', 'lamp-vine-10000-disposable', 'High-capacity disposable with adjustable airflow and battery indicator.', 2499, 'disposables', 'Lamp & Vine', 'disp-003', true, true);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-disp-004', 'Tampa Bay Vapor Co. Variety 3-Pack', 'tampa-bay-vapor-variety-3-pack', 'Three best-selling flavors bundled at a discount.', 3999, 'disposables', 'Tampa Bay Vapor Co.', 'disp-004', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-eliq-001', 'Desert Ember Nic Salt 30mL', 'desert-ember-nic-salt-30ml', 'Smooth nic salt e-liquid, available in multiple strengths.', 1999, 'e-liquids', 'Desert Ember', 'eliq-001', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-eliq-002', 'Cloud Peak Freebase 60mL', 'cloud-peak-freebase-60ml', 'Classic freebase e-liquid in a 60mL chubby gorilla bottle.', 2299, 'e-liquids', 'Cloud Peak', 'eliq-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-eliq-003', 'Bazaar Blend Menthol Ice 30mL', 'bazaar-blend-menthol-ice-30ml', 'Cooling menthol nic salt blend.', 1999, 'e-liquids', 'Bazaar Blend', 'eliq-003', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-glass-001', 'Oasis Beaker Water Pipe 12"', 'oasis-beaker-water-pipe-12in', 'Thick borosilicate glass beaker base with ice pinch and diffused downstem.', 7999, 'glass', 'Oasis', 'glass-001', true, true);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-glass-002', 'Northbound Spoon Hand Pipe', 'northbound-spoon-hand-pipe', 'Compact color-changing glass spoon pipe with deep bowl.', 2499, 'glass', 'Northbound', 'glass-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-glass-003', 'Ember & Oak Mini Bubbler', 'ember-oak-mini-bubbler', 'Compact bubbler with built-in percolator for smoother hits.', 4499, 'glass', 'Ember & Oak', 'glass-003', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-glass-004', 'Lamp & Vine Recycler Rig 8"', 'lamp-vine-recycler-rig-8in', 'Scientific-glass recycler with dual chamber filtration.', 8999, 'glass', 'Lamp & Vine', 'glass-004', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-hookah-001', 'Sultan''s Reserve 32" Hookah', 'sultans-reserve-32in-hookah', 'Traditional Egyptian-style hookah with stainless steel stem and washable hose.', 8999, 'hookah', 'Sultan''s Reserve', 'hookah-001', true, true);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-hookah-002', 'Bazaar Blend Double Apple Shisha 250g', 'bazaar-blend-double-apple-shisha-250g', 'Classic double apple flavored shisha tobacco.', 1599, 'hookah', 'Bazaar Blend', 'hookah-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-hookah-003', 'Genie''s Choice Natural Coconut Coals', 'genies-choice-coconut-coals', 'Long-burning natural coconut hookah coals, 1kg box.', 1899, 'hookah', 'Genie''s Choice', 'hookah-003', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-hookah-004', 'Desert Ember Hookah Heat Management Device', 'desert-ember-heat-management-device', 'Wind-cover style heat management device for a more even bowl.', 2299, 'hookah', 'Desert Ember', 'hookah-004', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-papers-001', 'Northbound Unbleached Rolling Papers', 'northbound-unbleached-rolling-papers', 'King-size unbleached rolling papers, pack of 50 leaves.', 299, 'papers', 'Northbound', 'papers-001', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-papers-002', 'Cloud Peak Pre-Rolled Cones (6-pack)', 'cloud-peak-pre-rolled-cones-6pack', 'Pre-rolled cones with built-in filter tip, ready to pack.', 499, 'papers', 'Cloud Peak', 'papers-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-papers-003', 'Ember & Oak Flavored Hemp Wraps (4-pack)', 'ember-oak-flavored-hemp-wraps', 'Slow-burning flavored hemp wraps.', 399, 'papers', 'Ember & Oak', 'papers-003', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-grind-001', 'Oasis 4-Piece Aluminum Grinder 2.5"', 'oasis-4-piece-aluminum-grinder', 'CNC-machined aluminum grinder with diamond-shaped teeth and pollen catcher.', 2499, 'grinders', 'Oasis', 'grind-001', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-grind-002', 'Lamp & Vine Electric Herb Grinder', 'lamp-vine-electric-herb-grinder', 'Battery-powered automatic grinder for fast, consistent grinds.', 3999, 'grinders', 'Lamp & Vine', 'grind-002', true, true);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-light-001', 'Desert Ember Triple Jet Torch Lighter', 'desert-ember-triple-jet-torch', 'Windproof triple-flame torch lighter, refillable butane.', 1999, 'lighters', 'Desert Ember', 'light-001', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-light-002', 'Bazaar Blend Classic Flint Lighter (5-pack)', 'bazaar-blend-classic-flint-lighter-5pack', 'Everyday disposable flint lighters, assorted colors.', 699, 'lighters', 'Bazaar Blend', 'light-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-acc-001', 'Northbound Rolling Tray Set', 'northbound-rolling-tray-set', 'Metal rolling tray with removable magnetic lid, medium size.', 1799, 'accessories', 'Northbound', 'acc-001', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-acc-002', 'Genie''s Choice Odor-Proof Storage Case', 'genies-choice-odor-proof-case', 'Smell-proof carbon-lined storage case with combination lock.', 3499, 'accessories', 'Genie''s Choice', 'acc-002', true, true);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-acc-003', 'Ember & Oak Glass Cleaning Kit', 'ember-oak-glass-cleaning-kit', 'Reusable cleaning solution and brush set for glass pieces.', 1499, 'accessories', 'Ember & Oak', 'acc-003', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-app-001', 'Ali Baba Smoke Shop Logo Tee', 'ali-baba-logo-tee', 'Soft cotton tee with the shop logo on the front.', 2499, 'apparel', 'Ali Baba Smoke Shop', 'app-001', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-app-002', 'Ali Baba Smoke Shop Snapback Hat', 'ali-baba-snapback-hat', 'Embroidered logo snapback, adjustable fit.', 2999, 'apparel', 'Ali Baba Smoke Shop', 'app-002', true, false);
insert into products (id, name, slug, description, price_cents, category_slug, brand, image_seed, in_stock, featured) values ('prod-app-003', 'Ali Baba Smoke Shop Sticker Pack', 'ali-baba-sticker-pack', 'Set of 5 vinyl stickers featuring shop artwork.', 699, 'apparel', 'Ali Baba Smoke Shop', 'app-003', true, false);
